export enum PrimitiveType {
  THREE_SIDED_FLAT_NO_TEXTURE_SOLID = '3_SIDED_FLAT_NO_TEXTURE_SOLID',
  THREE_SIDED_GOURAD_NO_TEXTURE_SOLID = '3_SIDED_GOURAD_NO_TEXTURE_SOLID',
  THREE_SIDED_GOURAD_TEXTURE = '3_SIDED_GOURAD_TEXTURE',
  THREE_SIDED_FLAT_TEXTURE = '3_SIDED_FLAT_TEXTURE',
}